title: 'My Interesting Nagging'
description: 'Still Single'
keywords: 'security'
url: 'https://Earthwater.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  Index: '/'
  Tag: '/tags.html'
  Timeline: '/timeline.html'
  AboutMe: '/about.html'
  Fri-Link: '/friendLink.html'

author: true
name: 'Earthwater/Tendoyo'
NickName: 'Tendoyo'
webtitle: 'My Interesting Nagging'
bio: 'Two sayings about deceit are best:<br>(1)lie involving half Truth is the most spiteful <br>(2)Real Truth always has a mask of lie'
about: true
aboutyou: 'Phd candidate in FuDan Univ.'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: [Facebook, weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']

paginate: 5
paginatepath: ['page:num']

footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

pygmentsTheme: 'emacs'

friends:
  jekyll: 'null'

disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js

livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment OAuth Application
Gitment: false
Gitment_owner: 'Earthwater'
Gitment_repo: ''
client_id: ''
client_secret: ''

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# Baidu Statics
baidu: true
baidu-url: ''
# Google Statics
google: false
google-ID: ''

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
